/**********************************************************************
 * Copyright (c) 2012 by the President and Fellows of Harvard College
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 *
 * Contact information
 *
 * Office for Information Systems
 * Harvard University Library
 * Harvard University
 * Cambridge, MA  02138
 * (617)495-3724
 * hulois@hulmail.harvard.edu
 **********************************************************************/

package edu.harvard.lib.librarycloud.items;

import java.util.List;

import javax.xml.bind.annotation.XmlElement;

import edu.harvard.lib.librarycloud.items.mods.ModsType;

/**
*
* Item is a wrapper class for item data. Currently this contains only a ModsType object, but eventually
* there may be other kids of data to wrap with mods in an item element. If mods extensions are used
* to embed data, rather than a library cloud schema containing mods and other data sections, this
* additional level of wrapper could be eliminated.
* ModsType maps to the "originaMods" solr field that contains an escaped mods xml document; 
* ModsType is the top-level object that maps to the <mods> root element 
* (generated by LOC from the mods schema); child classes exist for all possible child elements
* (see gov.loc.mods.v3 package)
* 
*  @author Michael Vandermillen
*
*/

public class Item {
	
	public Item () {
		
	}

	private ModsType modsType;
	
	@XmlElement(name = "mods", namespace = "http://www.loc.gov/mods/v3")
	public ModsType getModsType() {
		
		return modsType;
	}
	
	public void setModsType(ModsType modsType) {
		this.modsType = modsType;
	}


	//the old way was to add a list of ModsTypes to an item
	/*
	private List<ModsType> modsTypes;
	
	@XmlElement(name = "mods", namespace = "http://www.loc.gov/mods/v3")
	public List<ModsType> getModsTypes() {
		return modsTypes;
	}
	
	public void setModsTypes(List<ModsType> modsTypes) {
		this.modsTypes = modsTypes;
	}
	*/	
	
}
