curl -X POST -H 'Content-type:application/json' --data-binary '{
  "replace-field":{
    "name":"originDate",
    "type":"string",
    "stored":true,
    "indexed":true,
    "multiValued":true
     },
  "add-field":{
    "name":"subject.name.role",
    "type":"string",
    "stored":true,
    "indexed":true,
    "multiValued":true
  },
  "add-field":{
    "name":"subject.name.role_keyword",
    "type":"string",
    "stored":false,
    "indexed":true,
    "multiValued":true
  },
  "add-copy-field":{
    "source":"subject.name.role",
    "dest":"subject.name.role_keyword"
  },
  "add-field":{
    "name":"url.access.preview",
    "type":"boolean",
    "stored":false,
    "indexed":true
  },
  "add-field":{
    "name":"url.access.raw_object",
    "type":"boolean",
    "stored":false,
    "indexed":true
  }
}' http://$SOLR_HOST:$SOLR_PORT/solr/librarycloud/schema
