//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.02 at 03:34:01 PM MST 
//

package gov.loc.mods.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for modsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="modsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.loc.gov/mods/v3}modsGroup" maxOccurs="unbounded"/>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="version" type="{http://www.loc.gov/mods/v3}versionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/*
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "modsType", propOrder = {
    "modsGroup"
})
*/
@XmlRootElement(name = "mods")
@XmlAccessorType(XmlAccessType.FIELD)
public class ModsType {
	
    @XmlElements({
        @XmlElement(name = "part", type = PartType.class),
        @XmlElement(name = "language", type = LanguageType.class),
        @XmlElement(name = "note", type = NoteType.class),
        @XmlElement(name = "identifier", type = IdentifierType.class),
        @XmlElement(name = "classification", type = ClassificationType.class),
        @XmlElement(name = "titleInfo", type = TitleInfoType.class),
        @XmlElement(name = "extension", type = ExtensionType.class),
        @XmlElement(name = "accessCondition", type = AccessConditionType.class),
        @XmlElement(name = "typeOfResource", type = TypeOfResourceType.class),
        @XmlElement(name = "physicalDescription", type = PhysicalDescriptionType.class),
        @XmlElement(name = "tableOfContents", type = TableOfContentsType.class),
        @XmlElement(name = "subject", type = SubjectType.class),
        @XmlElement(name = "relatedItem", type = RelatedItemType.class),
        @XmlElement(name = "genre", type = GenreType.class),
        @XmlElement(name = "recordInfo", type = RecordInfoType.class),
        @XmlElement(name = "originInfo", type = OriginInfoType.class),
        @XmlElement(name = "location", type = LocationType.class),
        @XmlElement(name = "name", type = NameType.class),
        @XmlElement(name = "abstract", type = AbstractType.class),
        @XmlElement(name = "targetAudience", type = TargetAudienceType.class)
    })
    
    
    protected List<Object> modsGroup;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute
    protected String version;

    /**
     * Gets the value of the modsGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modsGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModsGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartType }
     * {@link LanguageType }
     * {@link NoteType }
     * {@link IdentifierType }
     * {@link ClassificationType }
     * {@link TitleInfoType }
     * {@link ExtensionType }
     * {@link AccessConditionType }
     * {@link TypeOfResourceType }
     * {@link PhysicalDescriptionType }
     * {@link TableOfContentsType }
     * {@link SubjectType }
     * {@link RelatedItemType }
     * {@link GenreType }
     * {@link RecordInfoType }
     * {@link OriginInfoType }
     * {@link LocationType }
     * {@link NameType }
     * {@link AbstractType }
     * {@link TargetAudienceType }
     * 
     * 
     */
    public List<Object> getModsGroup() {
        if (modsGroup == null) {
            modsGroup = new ArrayList<Object>();
        }
        return this.modsGroup;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
