//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.02 at 03:34:01 PM MST 
//


package gov.loc.mods.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for titleInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="titleInfoType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.loc.gov/mods/v3}baseTitleInfoType">
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="abbreviated"/>
 *             &lt;enumeration value="translated"/>
 *             &lt;enumeration value="alternative"/>
 *             &lt;enumeration value="uniform"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "titleInfoType")
public class TitleInfoType
    extends BaseTitleInfoType
{

    @XmlAttribute(name = "type")
    protected String tiType;

    /**
     * Gets the value of the tiType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTiType() {
        return tiType;
    }

    /**
     * Sets the value of the tiType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTiType(String value) {
        this.tiType = value;
    }

}
