/**********************************************************************
 * Copyright (c) 2012 by the President and Fellows of Harvard College
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA.
 *
 * Contact information
 *
 * Office for Information Systems
 * Harvard University Library
 * Harvard University
 * Cambridge, MA  02138
 * (617)495-3724
 * hulois@hulmail.harvard.edu
 **********************************************************************/

package edu.harvard.lib.lcloud;

import java.util.List;

import javax.xml.bind.annotation.XmlElement;

import gov.loc.mods.v3.ModsType;

/**
*
* Item is a wrapper class that contains a list of one or more ModsType objects within a SearchResults object.
* (modsType maps to the "originaMods" solr field that contains an escaped mods xml document; 
* ModsType is the top-level object that maps to the <mods> root element 
* (generated by LOC from the mods schema)
* 
*  @author Michael Vandermillen
*
*/

public class Item {
	
	public Item () {
		
	}
	
	private List<ModsType> modsTypes;
	
	@XmlElement(name = "mods", namespace = "http://www.loc.gov/mods/v3")
	public List<ModsType> getModsTypes() {
		return modsTypes;
	}
	
	public void setModsTypes(List<ModsType> modsTypes) {
		this.modsTypes = modsTypes;
	}
	
/*
	private ModsType modsType;
	
	@XmlElement(name = "mods", namespace = "http://www.loc.gov/mods/v3")
	public ModsType getModsType() {
		
		return modsType;
	}
	
	public void setModsType(ModsType modsType) {
		this.modsType = modsType;
	}
*/
}
